### ISSUE TITLE
Card? 

### ISSUE THREAD

**Issue by Nirsir** [hoglet67/ADFS#5]
After srloading adfs and unplugging all other rooms all I get is card? I am using turbo mmc with hoglet image for sd card.

**Comment by hoglet67** [comment]
It would be helpful to post a photo of your TurboMMC interface.

Check you are using the SDT rom version.

**Comment by Nirsir** [comment]
I am using the sd rom file from adfs 1.57, which should be the user port version. 
![Uploading IMG_20220511_134150.jpg…]()

**Comment by hoglet67** [comment]
The SDT ROM file is for User port connected Turbo MMC

The SD ROM file is for User port connected he original (non-Turbo) MMC

 I can't see the photo.

**Comment by Nirsir** [comment]
Do you have a compiled rom image for the turbo?

**Comment by hoglet67** [comment]
I've added a new build that includes the turbo versions:
https://github.com/hoglet67/ADFS/releases/tag/20220511_2024

One more thing: as this is based on ADFS 1.50 it will only work on the BBC Master.

**Comment by Nirsir** [comment]
That's perfect thank you

**Comment by Nirsir** [comment]
It's working perfectly now thank you again for your time
